#!/bin/sh
#
# chkconfig:   - 98 02
# description: Start vmware-discovery	  

### BEGIN INIT INFO
# Provides:
# Required-Start: $remote_fs $network $syslog
# Required-Stop: $remote_fs $syslog
# Default-Stop: 0 1 6
# Short-Description: Vsettan Nova Discovery worker
# Description: Discovers the VMware environment
#              *Instances
#              *Templates
#              *Networks
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=vmware-discovery
basepath=/usr/lib/python2.7/site-packages/vmware_discovery
exec="/usr/bin/vmware-discovery"
pidfile="/var/run/$prog.pid"
logfile="/var/log/$prog.log"

vmwareconf="/etc/vmware-discovery.conf"

[ -e /etc/nova/vmware-discovery.conf ] && vmwareconf="/etc/nova/vmware-discovery.conf"

configfiles=" --config-file $vmwareconf

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -f $exec ] || exit 5
    [ -x $exec ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user nova --pidfile $pidfile "$exec $configfiles --logfile $logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
